mysql:
  database: root:root@tcp(127.0.0.1:3306)/ginchat?charset=utf8mb4&parseTime=True&loc=Local

jwt:
  secret: "qwertyuioplkjhgfdsa4456mnvcxz"
  expire: "24"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  poolSize: 30
  minIdleConns: 30
